import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const cardWidth = width / 2 - 24; // Dynamic width for two-column layout

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(240, 248, 255, 0.75)", // Soft blue-white overlay
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderBottomWidth: 1.5,
    borderBottomColor: "#BAE6FD",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1E40AF",
    textAlign: "center",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  noteContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#BAE6FD",
    overflow: "hidden",
  },
  noteImage: {
    width: 90,
    height: 90,
    borderRadius: 12,
    resizeMode: "cover",
    marginBottom: 12,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#E0F7FA",
  },
  noteText: {
    fontSize: 17,
    fontWeight: "500",
    color: "#1F2937",
    textAlign: "center",
    lineHeight: 24,
    flexWrap: "wrap",
    maxWidth: "90%",
  },
  productList: {
    paddingHorizontal: 8,
    paddingBottom: 24,
  },
  productCard: {
    width: cardWidth,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 14,
    margin: 8,
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 340,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: "#E0F7FA",
    overflow: "hidden",
  },
  productImage: {
    width: 120,
    height: 120,
    resizeMode: "contain",
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: "#EFF6FF",
  },
  productName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E293B",
    textAlign: "center",
    flexWrap: "wrap",
    maxWidth: "100%",
    marginVertical: 4,
    lineHeight: 22,
    numberOfLines: 2,
    ellipsizeMode: "tail",
  },
  productPrice: {
    fontSize: 18,
    fontWeight: "700",
    color: "#047857",
    marginVertical: 6,
  },
  priceUnit: {
    fontSize: 15,
    fontWeight: "500",
    color: "#047857",
  },
  addToCartButton: {
    backgroundColor: "#20A920",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    width: "92%",
    marginTop: 10,
    marginBottom: 12,
    shadowColor: "#F97316",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 4,
  },
  addToCartText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  ageText: {
    fontSize: 14,
    fontWeight: "400",
    color: "#6B7280",
    textAlign: "center",
    marginVertical: 4,
  },
});