import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 50, 80, 0.4)", // Darker aquatic overlay
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginTop: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#004D40",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 15,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E0F2F1",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#26A69A",
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#004D40",
    paddingVertical: 10,
  },
  searchIcon: {
    paddingHorizontal: 10,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginLeft: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  filterText: {
    marginLeft: 5,
    fontSize: 16,
    fontWeight: "600",
    color: "#004D40",
  },
  filterDrawer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 300,
    height: "100%",
    backgroundColor: "#FFFFFF",
    padding: 20,
    zIndex: 1001,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 1000,
  },
  filterHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E0F2F1",
  },
  filterTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#004D40",
  },
  filterScrollContainer: {
    paddingBottom: 20,
  },
  filterSection: {
    marginBottom: 20,
  },
  filterSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
  },
  filterLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: "#004D40",
  },
  filterOptions: {
    paddingHorizontal: 10,
  },
  filterOption: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    backgroundColor: "#E0F2F1",
    marginBottom: 8,
  },
  selectedOption: {
    backgroundColor: "#26A69A",
  },
  filterOptionText: {
    fontSize: 14,
    color: "#004D40",
    fontWeight: "500",
  },
  selectedOptionText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  productList: {
    paddingHorizontal: 10,
    paddingBottom: 100,
  },
  productCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 12,
    margin: 6,
    height: 280,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    flexDirection: "column",
    justifyContent: "space-between",
  },
  productImage: {
    width: "100%",
    height: 120,
    resizeMode: "cover",
    borderRadius: 12,
  },
  textContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  productName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#004D40",
    textAlign: "center",
    maxHeight: 40, // Fixed height for 2 lines
    lineHeight: 20,
  },
  shopName: {
    fontSize: 12,
    fontWeight: "500",
    color: "#00695C",
    marginVertical: 4,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: "700",
    color: "#004D40",
  },
  buttonContainer: {
    width: "100%",
    alignItems: "center",
  },
  addToCartButton: {
    backgroundColor: "#26A69A",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: "center",
    width: "100%",
  },
  addToCartText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
    paddingBottom: 20,
  },
  paginationButton: {
    backgroundColor: "#E0F2F1",
    borderRadius: 12,
    padding: 10,
    marginHorizontal: 10,
  },
  disabledButton: {
    backgroundColor: "#E0E0E0",
    opacity: 0.5,
  },
  pageText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#004D40",
  },
  outOfStockCard: {
    backgroundColor: "#F5F5F5",
    opacity: 0.7,
  },
  outOfStockImage: {
    opacity: 0.6,
  },
  outOfStockButton: {
    backgroundColor: "#B0BEC5",
  },
  outOfStockText: {
    color: "#37474F",
    fontWeight: "600",
  },
  cartFab: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#26A69A",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    zIndex: 100,
  },
});