import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  background: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  scrollContent: {
    paddingTop: 20,
    paddingBottom: 100,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  headerIcon: {
    fontSize: 28,
    color: "#26A69A",
    marginRight: 15,
  },
  headerDate: {
    fontSize: 16,
    fontWeight: "700",
    color: "#004D40",
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#004D40",
  },
  titleContainer: {
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#004D40",
    marginBottom: 8,
  },
  dateTime: {
    fontSize: 16,
    fontWeight: "500",
    color: "#00695C",
    lineHeight: 22,
  },
  detailsContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0F2F1",
  },
  description: {
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0F2F1",
  },
  detailLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#004D40",
  },
  detailValueContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  typeDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginRight: 10,
  },
  detailValue: {
    fontSize: 16,
    fontWeight: "500",
    color: "#004D40",
  },
  dropdownIcon: {
    fontSize: 16,
    color: "#26A69A",
    marginLeft: 10,
  },
  dropdownContainer: {
    backgroundColor: "#E0F2F1",
    borderWidth: 2,
    borderColor: "#26A69A",
    borderRadius: 12,
    marginTop: 5,
    position: "absolute",
    right: 0,
    top: "100%", // Position below the detailValueContainer
    width: 120,
    zIndex: 1000,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  dropdownItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E0F2F1",
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#004D40",
    fontWeight: "500",
  },
  gifContainer: {
    alignItems: "center",
    marginTop: 20,
    zIndex: 0, // Ensure GIF is below dropdown
  },
  gif: {
    width: 250,
    height: 150,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#26A69A",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  addSaltButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#26A69A",
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    zIndex: 100,
  },
  addSaltButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
});