import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 60,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1A3C6D",
    textAlign: "center",
    marginVertical: 24,
    letterSpacing: 0.5,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2E4A7D",
    marginBottom: 16,
  },
  dropdown: {
    marginBottom: 150,
    borderColor: "#4A90E2",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#F9FBFF",
  },
  dropdownContainer: {
    zIndex: 100,
    borderColor: "#4A90E2",
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#F9FBFF",
  },
  symptomCard: {
    marginTop: 20,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    zIndex: 1,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 12,
    color: "#1A3C6D",
  },
  symptomList: {
    maxHeight: 120,
    zIndex: 1,
  },
  symptomItem: {
    paddingVertical: 6,
  },
  symptomText: {
    fontSize: 16,
    color: "#4A5568",
    lineHeight: 22,
  },
  nextButton: {
    position: "absolute",
    bottom: 30,
    right: 24,
    backgroundColor: "#4A90E2",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 30,
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  nextButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "85%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  modalText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1A3C6D",
    textAlign: "center",
    marginBottom: 16,
  },
  modalSubText: {
    fontSize: 15,
    fontWeight: "400",
    color: "#4A5568",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 22,
  },
  selector: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F9FBFF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4A90E2",
    width: "80%",
  },
  selectorText: {
    fontSize: 16,
    color: "#1A3C6D",
    fontWeight: "500",
  },
  dropdown1: {
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4A90E2",
    marginBottom: 12,
    width: "80%",
    maxHeight: 1000,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#4A5568",
    fontWeight: "500",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "80%",
    marginTop: 12,
  },
  confirmButton: {
    backgroundColor: "#4A90E2",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
  },
  confirmButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  closeButton: {
    backgroundColor: "#E53E3E",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});