import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  listContent: {
    paddingTop: 50,
    paddingBottom: 100, // Space for fixed button
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#004D40",
    textAlign: "center",
    marginVertical: 20,
    letterSpacing: 1,
    fontFamily: "System",
  },
  subTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: "#00695C",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 24,
  },
  dropdown: {
    borderColor: "#26A69A",
    borderWidth: 2,
    borderRadius: 12,
    backgroundColor: "#E0F2F1",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  dropdownContainer: {
    zIndex: 1000, // Above cards and button
    borderColor: "#26A69A",
    borderWidth: 2,
    borderRadius: 12,
    backgroundColor: "#E0F2F1",
    marginTop: 5,
  },
  symptomCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1, // Below button
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#004D40",
    marginBottom: 12,
  },
  symptomList: {
    maxHeight: 150, // Limit height to avoid scrolling conflicts
  },
  symptomItem: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E0F2F1",
  },
  symptomText: {
    fontSize: 16,
    color: "#37474F",
    lineHeight: 22,
  },
  nextButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#26A69A",
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    zIndex: 100, // Above cards, below dropdown
  },
  nextButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    width: "90%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  modalText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#004D40",
    textAlign: "center",
    marginBottom: 16,
  },
  modalSubText: {
    fontSize: 16,
    fontWeight: "400",
    color: "#455A64",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 24,
  },
  selector: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#E0F2F1",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#26A69A",
    width: "85%",
    marginBottom: 12,
  },
  selectorText: {
    fontSize: 16,
    color: "#004D40",
    fontWeight: "500",
  },
  dropdown1: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#26A69A",
    width: "85%",
    maxHeight: 1000,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0F2F1",
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#37474F",
    fontWeight: "500",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "85%",
    marginTop: 16,
  },
  confirmButton: {
    backgroundColor: "#26A69A",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    flex: 1,
    marginRight: 10,
  },
  confirmButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  closeButton: {
    backgroundColor: "#EF5350",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    flex: 1,
    marginLeft: 10,
  },
  closeButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});
